### ISSUE TITLE
subgraph package is not usable because of missing `abis` directory

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/subgraph#419]
Trying to run the ofllowing script will not work:
```

const Subgraph = require('@daostack/subgraph');

void async function() {
  Subgraph.setupEnv({
    subgraphName: 'daostack'
  })
}();

```
It throws: 
```
Deploying a new subgraph using the following settings:
{ subgraphName: 'daostack',
  migrationFile: '@daostack/migration/migration.json' }
Generating ABI files
Generating schemas
Generating subgraph
(node:26560) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, scandir '/home/jelle/projects/daostack/test_env/node_modules/@daostack/subgraph/ops/../abis'
    at Object.readdirSync (fs.js:790:3)
    at forEachTemplate (/home/jelle/projects/daostack/test_env/node_modules/@daostack/subgraph/ops/utils.js:10:29)
    at buildTemplates (/home/jelle/projects/daostack/test_env/node_modules/@daostack/subgraph/ops/generate-subgraph.js:171:3)
    at generateSubgraph (/home/jelle/projects/daostack/test_env/node_modules/@daostack/subgraph/ops/generate-subgraph.js:42:21)
    at Object.setupenv [as setupEnv] (/home/jelle/projects/daostack/test_env/node_modules/@daostack/subgraph/ops/setup-env.js:32:44)
(node:26560) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:26560) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by ben-kaufman** [comment]
@jellegerbrandy I'm unable to replicate the issue. Running the script works properly on my end. Please make sure you have the latest subgraph package and that the graph node is running.
